# Generated by Django 5.0.6 on 2024-05-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user_balance',
        ),
    ]
